version: '3.4'

services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
     - "6379:6379"
    environment:
     - REDIS_REPLICATION_MODE=master
  
  app:
    image: ${DOCKER_REGISTRY-}cteleportairportmeasureapi
    build:
      context: .
      dockerfile: sources/presentation/cTeleport.AirportMeasure.Api/Dockerfile
    environment:
     - ASPNETCORE_redisCache__connectionString=redis,password=sOmE_sEcUrE_pAsS
     - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - redis