version: '3.4'

services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master

  cteleport:
    image: dotronglong/faker:stable
    volumes:
      - ./tests/mocks:/app/mocks
    ports:
      - "3030:3030"

  app:
    image: ${DOCKER_REGISTRY-}cteleportairportmeasureapi
    build:
      context: .
      dockerfile: sources/presentation/cTeleport.AirportMeasure.Api/Dockerfile
    environment:
      - ASPNETCORE_redisCache__connectionString=redis
      - ASPNETCORE_ConnectionStrings__CTeleportUrl=http://cteleport:3030/
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
      - redis
      - cteleport
    ports:
      - "80"
      - "443"

  integration:
    depends_on:
      - app
      - redis
      - cteleport
    environment:
      - apiUrl=http://app
    build:
      context: ./tests/presentation/cTeleport.AirportMeasure.Api.ComponentTests/
      dockerfile: Dockerfile