version: '3.4'

services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master

  cteleport:
    image: dotronglong/faker:stable
    volumes:
      - ./tests/mocks:/app/mocks
    ports:
      - "3030:3030"

  app:
    image: ${DOCKER_REGISTRY-}cteleportairportmeasureapi
    build:
      context: .
      dockerfile: sources/presentation/cTeleport.AirportMeasure.Api/Dockerfile
    environment:
      - ASPNETCORE_redisCache__connectionString=redis
      - ASPNETCORE_ConnectionStrings__CTeleportUrl=http://cteleport:3030/
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123123Gh
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - redis
      - cteleport
    ports:
      - "80"
      - "443"
    volumes:
      - ~/.aspnet/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro